import { MarkerIconsLinks } from "./marker-icons-links.enum";

export const ApiIconTypeMapping: { [index: string]: MarkerIconsLinks } = {
	restaurant: MarkerIconsLinks.Food,
	cafe: MarkerIconsLinks.Cafe,
	bank: MarkerIconsLinks.Bank,
	gas_station: MarkerIconsLinks.Fuel,
	museum: MarkerIconsLinks.Culture,
	park: MarkerIconsLinks.Nature,
	church: MarkerIconsLinks.Religion,
	department_store: MarkerIconsLinks.Shopping,
	shopping_mall: MarkerIconsLinks.Shopping,
	night_club: MarkerIconsLinks.Adult,
	gym: MarkerIconsLinks.Sport,
	amusement_park: MarkerIconsLinks.Entertainment,
	lodging: MarkerIconsLinks.Sleep,
	movie_theater: MarkerIconsLinks.Entertainment,
	zoo: MarkerIconsLinks.Nature,
	art_gallery: MarkerIconsLinks.Culture,
	stadium: MarkerIconsLinks.Sport,
	car_dealer: MarkerIconsLinks.Car,
	car_rental: MarkerIconsLinks.Car,
	car_repair: MarkerIconsLinks.Car,
	car_wash: MarkerIconsLinks.Car,
	bicycle_store: MarkerIconsLinks.Cycling,
	bar: MarkerIconsLinks.Adult,
	casino: MarkerIconsLinks.Adult,
	historical_landmark: MarkerIconsLinks.History,
	library: MarkerIconsLinks.Culture,
	school: MarkerIconsLinks.Misc,
	university: MarkerIconsLinks.Misc,
	city_hall: MarkerIconsLinks.Misc,
	local_government_office: MarkerIconsLinks.Misc,
	post_office: MarkerIconsLinks.Misc,
	fire_station: MarkerIconsLinks.Misc,
	police: MarkerIconsLinks.Misc,
	hospital: MarkerIconsLinks.Misc,
	doctor: MarkerIconsLinks.Misc,
	dentist: MarkerIconsLinks.Misc,
	pharmacy: MarkerIconsLinks.Misc,
	natural_feature: MarkerIconsLinks.Nature,
	campground: MarkerIconsLinks.Nature,
	rv_park: MarkerIconsLinks.Misc,
	general_contractor: MarkerIconsLinks.Industrial,
	factory: MarkerIconsLinks.Industrial,
	architect: MarkerIconsLinks.Architecture,
	point_of_interest: MarkerIconsLinks.Misc,
};
