export enum MarkerType {
	Food = "food",
	Misc = "misc",
	Car = "car",
	Bank = "bank",
	Cafe = "cafe",
	Fuel = "fuel",
	Adult = "adult",
	Sleep = "sleep",
	Sport = "sport",
	Nature = "nature",
	Culture = "culture",
	History = "history",
	Religion = "religion",
	Shopping = "shopping",
	Industrial = "industrial",
	Architecture = "architecture",
	Entertainment = "entertainment",
	Cycling = "cycling",
}
